# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
